# Generated by Django 5.1 on 2024-09-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_candy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='price',
            field=models.IntegerField(),
        ),
    ]
